### ISSUE TITLE
Puddles should not slow down the player, unlike vanilla water.

### ISSUE THREAD

**Issue by K0-RR** [TeamMidnightDust/Puddles#2]
It's just a little puddle to wet your socks. To be honest it's annoying when you are running.

**Comment by Motschen** [comment]
I can't really change that, since the puddle just uses the water fluid.

**Comment by RDKRACZ** [comment]
I forgot to mention that I got this suggestion after playing with Unearthed mod - it adds puddles (only generated by entering/leaving the water, not by rain) which don't slow don't your movement. They also have Targeted Fluid - minecraft:empty and for yours, it's water like you said. Maybe you could take a look at their implementation?

Is your mod server-side only? I'm not sure because it uses vanilla water but at the same time there is an obtainable (via /give) block so probably no.
Can you add information about the available config option (/gamerule) to the curseforge desc?

![image](https://user-images.githubusercontent.com/43277609/117960466-4c45d300-b31d-11eb-8855-6bca3ccf121c.png)
